// PROGRAMA SEMAFORO COM 3 LEDS

void setup()

{

pinMode(13,OUTPUT); // DEFINE O PINO 13 COMO OUTPUT, OU SEJA, UMA SAÍDA.
pinMode(12,OUTPUT); // DEFINE O PINO 12 COMO OUTPUT, OU SEJA, UMA SAÍDA.
pinMode(11,OUTPUT); // DEFINE O PINO 11 COMO OUTPUT, OU SEJA, UMA SAÍDA.

}

void loop()

{

digitalWrite(13,HIGH); // COLOCA O PINO 13 EM NÍVEL "ALTO", OU SEJA, EM 5 V; O LED VERMELHO ACENDE.
delay(5000); // TEMPO DE ESPERA DE 5 SEGUNDOS.
digitalWrite(13,LOW); // COLOCA O PINO 13 EM NÍVEL "BAIXO", OU SEJA, EM 0 V; O LED VERMELHO APAGA.

digitalWrite(11,HIGH); // COLOCA O PINO 11 EM NÍVEL "ALTO", OU SEJA, EM 5 V; O LED VERDE ACENDE.
delay(5000); // TEMPO DE ESPERA DE 5 SEGUNDOS.
digitalWrite(11,LOW); // COLOCA O PINO 11 EM NÍVEL "BAIXO", OU SEJA, EM 0 V; O LED VERDE APAGA.

digitalWrite(12,HIGH); // COLOCA O PINO 12 EM NÍVEL "ALTO", OU SEJA, EM 5 V; O LED AMARELO ACENDE.
delay(2000); // TEMPO DE ESPERA DE 2 SEGUNDOS.
digitalWrite(12,LOW); // COLOCA O PINO 12 EM NÍVEL "BAIXO", OU SEJA, 0 V; O LED AMARELO APAGA.

}
